apiVersion: v1
kind: Template
metadata:
  annotations:
    description: HTTP Test Services
    iconClass: icon-load-balancer
    tags: api,test
  name: ${APP_NAME}
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    replicas: ${{REPLICAS}}
    selector:
      matchLabels:
        app: ${APP_NAME}
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: ${APP_NAME}
      spec:
        containers:
        - image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: http-tests
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: ${APP_NAME}
          ports:
          - containerPort: 9092
            name: http-tests
            protocol: TCP
          env:
          - name: HTTP_TIMEOUT
            value: ${HTTP_TIMEOUT}
          - name: API_PREFIX
            value: ${API_PREFIX}
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: http-tests
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
        imagePullSecrets:
        - name: rh-registry-pull
        restartPolicy: Always
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APP_NAME}
    name: http-test-services
  spec:
    ports:
    - port: 9092
      protocol: TCP
      targetPort: 9092
    selector:
      app: ${APP_NAME}
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APP_NAME}
    name: http-test-services-grpc
  spec:
    ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      appProtocol: grpc
    selector:
      app: ${APP_NAME}
parameters:
- name: IMAGE_TAG
  required: true
- name: IMAGE
  value: quay.io/redhat-services-prod/hcc-accessmanagement-tenant/http-test-services
- description: Number of replicas for the deployment
  name: REPLICAS
  value: '2'
- description: Name for app in the deployment
  name: APP_NAME
  required: true
  value: http-test-services
- description: CPU limit for service
  name: CPU_LIMIT
  value: 300m
- description: Memory limit for service
  name: MEMORY_LIMIT
  value: 512Mi
- description: Requested CPU for service
  name: CPU_REQUEST
  value: 150m
- description: Requested memory for service
  name: MEMORY_REQUEST
  value: 256Mi
- description: HTTP server timeout in seconds
  name: HTTP_TIMEOUT
  value: '30'
- description: Path for the apis, defaults if not provided
  name: API_PREFIX
  value: ""
